src/main/java/com/beowulfe/hap/characteristics/BaseCharacteristic.java
src/main/java/com/beowulfe/hap/impl/characteristics/windowcovering/HoldPositionCharacteristic.java

I came up with 2 bugs when trying to implement a WindowCovering.
1. Got a null pointer exception in HoldPositionCharacteristic because getValue() returned null but should return a CompletableFuture.
2. After fixing that the created json looked like `"value": null`. Looks like HomeKit cannot handle null values. Completely omitting the value fixed the problem.
By the way: Nice work your HAP-Java :-)

Fix NPE in HoldPositionCharacteristic and null value in serialized characteristics

---

src/main/java/com/beowulfe/hap/accessories/ContactSensor.java
src/main/java/com/beowulfe/hap/accessories/MotionSensor.java
src/main/java/com/beowulfe/hap/accessories/properties/ContactState.java
src/main/java/com/beowulfe/hap/impl/characteristics/contactsensor/ContactSensorStateCharacteristic.java
src/main/java/com/beowulfe/hap/impl/characteristics/motionsensor/MotionDetectedStateCharacteristic.java
src/main/java/com/beowulfe/hap/impl/services/ContactSensorService.java
src/main/java/com/beowulfe/hap/impl/services/MotionSensorService.java

I couldn't wait until the weekend so here are my changes for adding motion sensors and contact sensors support. I tested this and things appear correctly in HomeKit apps.
In a future PR I will explore adding support for battery status. That information does not seem to be that accurate in my zwave sensors so it is low priority for now.
If you want me to create 2 PRs, one for motion sensor and one for contact sensor let me know.
Thanks,
Gaston

Added support for motion sensors and contact sensors

---

src/main/java/com/beowulfe/hap/accessories/CarbonMonoxideSensor.java
src/main/java/com/beowulfe/hap/accessories/SmokeSensor.java
src/main/java/com/beowulfe/hap/accessories/properties/CarbonMonoxideDetectedState.java
src/main/java/com/beowulfe/hap/accessories/properties/SmokeDetectedState.java
src/main/java/com/beowulfe/hap/impl/characteristics/carbonmonoxide/Carbon/CarbonMonoxideDetectedCharacteristic.java
src/main/java/com/beowulfe/hap/impl/characteristics/smokesensor/SmokeDetectedCharacteristic.java
src/main/java/com/beowulfe/hap/impl/services/CarbonMonoxideSensorService.java
src/main/java/com/beowulfe/hap/impl/services/SmokeSensorService.java

Finally got to finish these new sensors. They are working fine although I have not tested setting my house on fire. :)

Added support for carbon monoxide sensor and smoke sensor.

---

src/main/java/com/beowulfe/hap/accessories/SecuritySystem.java
src/main/java/com/beowulfe/hap/accessories/properties/CurrentSecuritySystemState.java
src/main/java/com/beowulfe/hap/accessories/properties/SecuritySystemAlarmType.java
src/main/java/com/beowulfe/hap/accessories/properties/TargetSecuritySystemState.java
src/main/java/com/beowulfe/hap/impl/characteristics/securitysystem/CurrentSecuritySystemStateCharacteristic.java
src/main/java/com/beowulfe/hap/impl/characteristics/securitysystem/SecuritySystemAlarmTypeCharacteristic.java
src/main/java/com/beowulfe/hap/impl/characteristics/securitysystem/TargetSecuritySystemStateCharacteristic.java
src/main/java/com/beowulfe/hap/impl/http/impl/AccessoryHandler.java
src/main/java/com/beowulfe/hap/impl/http/impl/BinaryHandler.java
src/main/java/com/beowulfe/hap/impl/services/SecuritySystemService.java

Andy,
Security system support has been added and "fully" tested. Also changed logging level to debug for connection timeouts as we talked.
Let me know if you have observations.
Thanks,
Gaston

Added support for security system. Logs were clean up as a bonus

---

src/main/java/com/beowulfe/hap/impl/characteristics/thermostat/TargetHeatingCoolingModeCharacteristic.java

Fixing issue with the targetMode of Thermostat implementations not being able to be set due to setting isWritable = false on TargetHeatingCoolingModeCharacteristic superclass.

Fixing TargetHeatingCoolingModeCharacteristic

---

src/main/java/com/beowulfe/hap/HomekitRoot.java
src/main/java/com/beowulfe/hap/accessories/LightSensor.java
src/main/java/com/beowulfe/hap/impl/HomekitRegistry.java
src/main/java/com/beowulfe/hap/impl/characteristics/common/Name.java
src/main/java/com/beowulfe/hap/impl/characteristics/light/AmbientLightLevelCharacteristic.java
src/main/java/com/beowulfe/hap/impl/http/impl/AccessoryHandler.java
src/main/java/com/beowulfe/hap/impl/http/impl/BinaryHandler.java
src/main/java/com/beowulfe/hap/impl/json/CharacteristicsController.java
src/main/java/com/beowulfe/hap/impl/services/AbstractServiceImpl.java
src/main/java/com/beowulfe/hap/impl/services/AccessoryInformationService.java
src/main/java/com/beowulfe/hap/impl/services/CarbonMonoxideSensorService.java
src/main/java/com/beowulfe/hap/impl/services/ContactSensorService.java
src/main/java/com/beowulfe/hap/impl/services/FanService.java
src/main/java/com/beowulfe/hap/impl/services/GarageDoorService.java
src/main/java/com/beowulfe/hap/impl/services/HumiditySensorService.java
src/main/java/com/beowulfe/hap/impl/services/LightSensorService.java
src/main/java/com/beowulfe/hap/impl/services/LightbulbService.java
src/main/java/com/beowulfe/hap/impl/services/LockMechanismService.java
src/main/java/com/beowulfe/hap/impl/services/MotionSensorService.java
src/main/java/com/beowulfe/hap/impl/services/OutletService.java
src/main/java/com/beowulfe/hap/impl/services/SecuritySystemService.java
src/main/java/com/beowulfe/hap/impl/services/SmokeSensorService.java
src/main/java/com/beowulfe/hap/impl/services/SwitchService.java
src/main/java/com/beowulfe/hap/impl/services/TemperatureSensorService.java
src/main/java/com/beowulfe/hap/impl/services/ThermostatService.java
src/main/java/com/beowulfe/hap/impl/services/WindowCoveringService.java

Andy,
Here are 2 small improvements:
1. It is now possible to specify service name. Still defaults to accessory label
2. Log IOExceptions using DEBUG level. Before it was only one type of timeout.
I have an accessory that  offers 2 services and both services were appearing with the same name (the name of the accessory). I added a new constructor to ServicesImpl so that we can pass a serviceName. Old constructor is still around and defaults to accessory label. 
Fine-prints: 1) Had to remove the deprecated constructor in AbstractServiceImpl. I think you were ok with this. 2) Changed constructor of Name to accept a String instead of a HomekitAccessory.
Noticed a few more "noisy" entries in the log around IOExceptions so went ahead and change code to log with DEBUG all IOExceptions instead of …

We can now specify service name

---

src/main/java/com/beowulfe/hap/characteristics/FloatCharacteristic.java
src/main/java/com/beowulfe/hap/impl/characteristics/carbonmonoxide/CarbonMonoxideDetectedCharacteristic.java
src/main/java/com/beowulfe/hap/impl/services/CarbonMonoxideSensorService.java

Andy,
After some detective work I was able to narrow down the reason the accessory was disappearing. I'm still running more tests to confirm this was the reason but so far after 24 hours it is holding fine. The problem was not in the code but in the data the accessory was returning. To be more precise, AmbientLightLevelCharacteristic said that values were in the range between 0.0001 and 100000. My zwave sensor was returning 0.0 when it was dark. Seems like HK runs some background check at some moment and if an accessory is returning some invalid data (e.g. value out of range) then it is declared as "incompatible" (I guess) and is silently removed.
I added a simple check in the library to detect out of range values (for Floats) and return closest value within range. The problem is also …

Returning value out of range made accessory disappear

---

src/main/java/com/beowulfe/hap/accessories/properties/TargetSecuritySystemState.java

As per the [Homekit documentation](https://developer.apple.com/documentation/homekit/hmcharacteristicvaluetargetsecuritysystemstate) the name of the constant for disarming the security system is `disarm` not `disarmed`, as this is the **Target**SecuritySystemState, not the **Current**SecuritySystemState.
I also updated the descriptions to be more in line with the intent of the `TargetSecuritySystemState` enum

Update the TargetSecuritySystemState enum

---

src/main/java/com/beowulfe/hap/accessories/properties/SecuritySystemAlarmType.java

Another small tweak to clean up an inconsistency [with the HomeKit documentation](https://developer.apple.com/documentation/homekit/hmcharacteristicvaluesecuritysystemalarmtype/1648623-noalarm) that I came across.
@beowulfe should be a quick one 😄

Update the SecuritySystemAlarmType enum

---

pom.xml

Had problems with building the software/javadoc on my Mac. 
* bumped mvn-plugin versions, to made build work with current Apache Maven 3.5.4
* added source encoding to make build independent of platform encoding

Maven update - Build stability

---

src/main/java/com/beowulfe/hap/accessories/BatteryAccessory.java
src/main/java/com/beowulfe/hap/accessories/BatteryStatusAccessory.java
src/main/java/com/beowulfe/hap/accessories/CarbonMonoxideSensor.java
src/main/java/com/beowulfe/hap/accessories/ContactSensor.java
src/main/java/com/beowulfe/hap/accessories/LockMechanism.java
src/main/java/com/beowulfe/hap/accessories/MotionSensor.java
src/main/java/com/beowulfe/hap/accessories/SmokeSensor.java
src/main/java/com/beowulfe/hap/impl/characteristics/common/LowBatteryStatusCharacteristic.java
src/main/java/com/beowulfe/hap/impl/services/AbstractServiceImpl.java

BatteryAccessory is used only by BatteryService and does not apply to MotionSensor, SmokeSensor, etc.
Deprecate BatteryAccessory and leave the implementation for BatteryService / Battery for a future date. Log a warning for accessories that are still trying to use it.

Add and direct implementors to use LowBatteryStatusAccessory

---

src/main/java/com/beowulfe/hap/accessories/BatteryAccessory.java
src/main/java/com/beowulfe/hap/accessories/BatteryStatusAccessory.java
src/main/java/com/beowulfe/hap/accessories/CarbonMonoxideSensor.java
src/main/java/com/beowulfe/hap/accessories/ContactSensor.java
src/main/java/com/beowulfe/hap/accessories/LeakSensor.java
src/main/java/com/beowulfe/hap/accessories/LockMechanism.java
src/main/java/com/beowulfe/hap/accessories/MotionSensor.java
src/main/java/com/beowulfe/hap/accessories/SmokeSensor.java
src/main/java/com/beowulfe/hap/accessories/Valve.java
src/main/java/com/beowulfe/hap/accessories/ValveWithTimer.java
src/main/java/com/beowulfe/hap/accessories/properties/ValveType.java
src/main/java/com/beowulfe/hap/impl/characteristics/common/ActiveCharacteristic.java
src/main/java/com/beowulfe/hap/impl/characteristics/common/InUseCharacteristic.java
src/main/java/com/beowulfe/hap/impl/characteristics/common/LowBatteryStatusCharacteristic.java
src/main/java/com/beowulfe/hap/impl/characteristics/common/RemainingDurationCharacteristic.java
src/main/java/com/beowulfe/hap/impl/characteristics/leaksensor/LeakDetectedStateCharacteristic.java
src/main/java/com/beowulfe/hap/impl/characteristics/valve/SetDurationCharacteristic.java
src/main/java/com/beowulfe/hap/impl/characteristics/valve/ValveTypeCharacteristic.java
src/main/java/com/beowulfe/hap/impl/services/AbstractServiceImpl.java
src/main/java/com/beowulfe/hap/impl/services/LeakSensorService.java
src/main/java/com/beowulfe/hap/impl/services/ValveService.java

In this PR, we add support for LeakSensor and Valve devices.

Add support for LeakSensor and Valve devices

---

src/main/java/com/beowulfe/hap/accessories/OccupancySensor.java
src/main/java/com/beowulfe/hap/impl/characteristics/occupancysensor/OccupancyDetectedStateCharacteristic.java
src/main/java/com/beowulfe/hap/impl/services/OccupancySensorService.java

Add support for occupancy sensors

OccupancySensor support

---

src/main/java/com/beowulfe/hap/impl/connections/LengthPrefixedByteArrayProcessor.java

we want to call step again if there's remaining data. pos + toWrite
is what we consumed from this network frame to complete the encrypted
frame. so if it's less than the total network frame (data.length),
then call step again.

fix reading encrypted frames that don't line up with network frames

---

src/main/java/com/beowulfe/hap/characteristics/BaseCharacteristic.java
src/main/java/com/beowulfe/hap/impl/json/AccessoryController.java

some minor optimizations to reduce the /accessories response size

Some streamlining

---

src/main/java/com/beowulfe/hap/HomekitServer.java
src/main/java/com/beowulfe/hap/impl/http/impl/HomekitHttpServer.java
src/main/java/com/beowulfe/hap/impl/http/impl/NettyHomekitHttpService.java

make sure we bind the HTTP server to the same address that we told
Bonjour to advertise. otherwise we might end up listening on some rando
interface that may not actually be able to accept connections

fix a pairing issue

---

src/main/java/com/beowulfe/hap/accessories/BasicWindowCovering.java
src/main/java/com/beowulfe/hap/accessories/HoldPositionWindowCovering.java
src/main/java/com/beowulfe/hap/accessories/ObstructionDetectedWindowCovering.java
src/main/java/com/beowulfe/hap/accessories/WindowCovering.java
src/main/java/com/beowulfe/hap/impl/characteristics/windowcovering/CurrentPositionCharacteristic.java
src/main/java/com/beowulfe/hap/impl/characteristics/windowcovering/HoldPositionCharacteristic.java
src/main/java/com/beowulfe/hap/impl/characteristics/windowcovering/PositionStateCharacteristic.java
src/main/java/com/beowulfe/hap/impl/characteristics/windowcovering/TargetPositionCharacteristic.java
src/main/java/com/beowulfe/hap/impl/services/WindowCoveringService.java

The pattern for most accessories is to require only the required
characteristics, and then allow the specification of optional characteristics
via the inclusion of interfaces. This pattern was not followed with
WindowCovering. Worse, for reasons currently not understood, the inclusion of
the HoldPositionCharacteristic causes the homekit pairing with the bridge to be
completely unresponsive. (See issue #56)
Change is made in a backwards compatible way, so that existing implementations
that depend on WindowCovering as implemented will continue to function
Addresses #56

Introduce BasicWindowCovering and deprecate WindowCovering

---

src/main/java/com/beowulfe/hap/impl/connections/PendingNotification.java
src/main/java/com/beowulfe/hap/impl/connections/SubscriptionManager.java
src/main/java/com/beowulfe/hap/impl/json/CharacteristicsController.java
src/main/java/com/beowulfe/hap/impl/json/EventController.java

I've been running this for several days on my home installation, and it's definitely improved responsiveness when asking Siri to do something that involves multiple accessories.

batch notifications when possible

---

.travis.yml
src/main/java/io/github/hapjava/impl/characteristics/garage/CurrentDoorStateCharacteristic.java
src/main/java/io/github/hapjava/impl/characteristics/garage/TargetDoorStateCharacteristic.java

the names for current and target state of the garage door were swapped. e.g. targetDoorState had no "setState" method.

fix the names of the garage door characteristics

---

.travis.yml
src/main/java/io/github/hapjava/accessories/TemperatureSensor.java
src/main/java/io/github/hapjava/impl/characteristics/thermostat/TemperatureUnitsCharacteristic.java

set target temperature is not working in ios13 as ios13 expected temperature unit (celsius, fahrenheit) to be changeable.  the temperature unit is used in homekit only for displaying purposes. at the protocol level the celsius is used as basis.
this patch makes temperature unit changeable.

#86 Fix thermostat for ios13

---

src/main/java/io/github/hapjava/impl/connections/HttpSession.java
src/main/java/io/github/hapjava/impl/json/AccessoryController.java
src/main/java/io/github/hapjava/impl/pairing/FinalPairHandler.java
src/main/java/io/github/hapjava/impl/pairing/PairingManager.java

ios13 evaluate sdiscoverability (sf flag) differently than older ios and stop pairing process if this flag changes (see issue #93). this PR fix it by keeping discoverability true

#93 Fix discoverability & pairing with ios13

---

src/test/java/io/github/hapjava/HomekitRootTest.java

Fixed package

---

.travis.yml
pom.xml
src/main/java/io/github/hapjava/accessories/CarbonDioxideSensor.java
src/main/java/io/github/hapjava/accessories/properties/CarbonDioxideDetectedState.java
src/main/java/io/github/hapjava/impl/characteristics/carbondioxide/CarbonDioxideDetectedCharacteristic.java
src/main/java/io/github/hapjava/impl/characteristics/carbondioxide/CarbonDioxideLevelCharacteristic.java
src/main/java/io/github/hapjava/impl/services/CarbonDioxideSensorService.java

add support for carbon dioxide sensor. implementation is similar to carbon monoxide sensor.

add carbon dioxide sensor

---

CHANGES.md
src/main/java/io/github/hapjava/accessories/HumidifierDehumidifierAccessory.java
src/main/java/io/github/hapjava/characteristics/impl/humidifier/TargetHumidifierDehumidifierStateCharacteristic.java
src/main/java/io/github/hapjava/services/impl/HumidifierDehumidifierService.java

add support for valid values for (de)Humidifier target state

---

CHANGES.md
src/main/java/io/github/hapjava/server/impl/HomekitRegistry.java
src/main/java/io/github/hapjava/server/impl/json/AccessoryController.java
src/main/java/io/github/hapjava/services/Service.java
src/main/java/io/github/hapjava/services/impl/AbstractServiceImpl.java

Some services require linked services to work, for example, the Television service which requires each input to be a linked service.
With this change, support to link services is added, though it's not used in any existing service, as they don't need linking. But I verified the functionality using my own Television service, which is not yet production-ready.
This change also centralizes the generation of interface ids. They are now only generated in the registry. 
We were previously also generating them in the accessory controller, relying on an identical processing sequence.
This is implementing the issue https://github.com/hap-java/HAP-Java/issues/104 and replacing PR https://github.com/hap-java/HAP-Java/pull/105. 
The author seems to have abandoned the PR and I personally also think …

add support for linked services

---

src/main/java/io/github/hapjava/server/HomekitAuthInfo.java
src/main/java/io/github/hapjava/server/impl/HomekitRoot.java
src/main/java/io/github/hapjava/server/impl/crypto/HAPSetupCodeUtils.java
src/main/java/io/github/hapjava/server/impl/jmdns/JmdnsHomekitAdvertiser.java
src/test/java/io/github/hapjava/server/impl/HomekitRootTest.java

add support for QRCode pairing. 
it consists of 2 parts:
- add setup code to mDNS advertisement 
- generate SetupURI that is the basis for QR code. 
fix for #121

add support for QR Code for pairing 

---

pom.xml
src/main/java/io/github/hapjava/server/impl/HomekitRoot.java
src/main/java/io/github/hapjava/server/impl/HomekitServer.java
src/main/java/io/github/hapjava/server/impl/HomekitStandaloneAccessoryServer.java
src/main/java/io/github/hapjava/server/impl/jmdns/JmdnsHomekitAdvertiser.java

porting the old PR with jmDNS enhancements to latest code base and updating jmDNS to latest stable version, which is 3.5.6

port of #68 PR on jmDNS to latest code base

---

CHANGES.md
README.md
src/main/java/io/github/hapjava/accessories/AirPurifierAccessory.java
src/main/java/io/github/hapjava/accessories/FilterMaintenanceAccessory.java
src/main/java/io/github/hapjava/accessories/optionalcharacteristic/AccessoryWithFilterLifeLevel.java
src/main/java/io/github/hapjava/accessories/optionalcharacteristic/AccessoryWithResetFilterIndication.java
src/main/java/io/github/hapjava/characteristics/impl/base/IntegerCharacteristic.java
src/main/java/io/github/hapjava/characteristics/impl/filtermaintenance/FilterChangeIndicationCharacteristic.java
src/main/java/io/github/hapjava/characteristics/impl/filtermaintenance/FilterChangeIndicationEnum.java
src/main/java/io/github/hapjava/characteristics/impl/filtermaintenance/FilterLifeLevelCharacteristic.java
src/main/java/io/github/hapjava/characteristics/impl/filtermaintenance/ResetFilterIndicationCharacteristic.java
src/main/java/io/github/hapjava/services/impl/AirPurifierService.java
src/main/java/io/github/hapjava/services/impl/FilterMaintenanceService.java

[#124](https://github.com/hap-java/HAP-Java/pull/124)

Add support for FilterMaintenanceAccessory

---

src/main/java/io/github/hapjava/characteristics/impl/garagedoor/CurrentDoorStateEnum.java

Fixes #131
Simple typo in `CurrentDoorStateEnum`: `SOPPED` should be `STOPPED`

fix typo in enum value

---

src/main/java/io/github/hapjava/characteristics/impl/base/BaseCharacteristic.java

"event" is payload parameter used to subscribe or unsubscribe to/from event notification. e.g. controller sends "event:true" to the HAP accessory if it wants to get event notifications.
it is unclear from the specification whether it should be sent with accessory description or not. it is marked as optional.  Java-HAP was always sending it with the value "false".
however, the recent version of home app stops working if this parameter is in the payload for some accessory types, e.g. ColorTemperature. (reported here https://github.com/openhab/openhab-addons/issues/9799 and here https://community.openhab.org/t/homekit-color-temperature-with-hue-bulbs/105658). I could also re-produce this behaviour. 
this PR removes "event" parameter from the payload.

Remove event parameter

---

.github/workflows/deploy.yml
README.md
pom.xml

Turns out wagon-scm doesn’t pick up the github properties the way the release plugin does. This fixes the site deploy.
Fixes #141 
- [n/a] For fixes, optimizations and new features, please add an entry to the CHANGES.md file.

Fix site-deploy

---

CHANGES.md
pom.xml
src/main/java/io/github/hapjava/server/impl/jmdns/JmdnsHomekitAdvertiser.java
src/test/java/io/github/hapjava/server/impl/jmdns/JmdnsHomekitAdvertiserTest.java

Fix for unregistering service when re-advertising

---

CHANGES.md
src/main/java/io/github/hapjava/server/impl/HomekitRoot.java

Fix: Log accessory names not futures

---

pom.xml

i think it is time to upgrade netty. there are many important fixes including log4j security fix.
the version is also align with OH netty version. 

upgrade netty to 4.1.72.Final

---

CHANGES.md
src/main/java/io/github/hapjava/accessories/optionalcharacteristic/AccessoryWithRotationSpeed.java
src/main/java/io/github/hapjava/characteristics/impl/fan/RotationSpeedCharacteristic.java

Rotation speed characteristic must be of type float according to apple HAP specification. 
we had it as integration. 
this PR change the data type to float. It change the interface so that implementation would need to adapt as well. 
it also makes min/max/step configurable.

Fix rotation speed type

---

CHANGES.md
src/main/java/io/github/hapjava/server/impl/json/AccessoryController.java
src/main/java/io/github/hapjava/server/impl/json/CharacteristicsController.java
src/main/java/io/github/hapjava/server/impl/json/EventController.java

reopening https://github.com/hap-java/HAP-Java/pull/148
all credits go to @gjvanderheiden 

close JsonWriters

---

src/main/java/io/github/hapjava/server/HomekitAccessoryCategories.java
src/main/java/io/github/hapjava/server/impl/HomekitRoot.java
src/main/java/io/github/hapjava/server/impl/HomekitServer.java
src/main/java/io/github/hapjava/server/impl/http/impl/AccessoryHandler.java
src/main/java/io/github/hapjava/server/impl/http/impl/DefaultHttpRequestImpl.java
src/main/java/io/github/hapjava/server/impl/http/impl/NettyResponseUtil.java
src/main/java/io/github/hapjava/server/impl/jmdns/JmdnsHomekitAdvertiser.java
src/test/java/io/github/hapjava/server/impl/HomekitRootTest.java
src/test/java/io/github/hapjava/server/impl/jmdns/JmdnsHomekitAdvertiserTest.java

- add support for HomeKit categories, so that bridge can pretend different accessory like Television
- add protocol version to mDNS parameters "pv":"1.1.". this is required according to HAP spec, but could not detect any difference until now. probably home app is not checking it
- replace netty deprecated methods. it looks like netty just did renaming of classes without changing the logic. 
i would make release after this PR if there are no objections. 

add support for HomeKit categories

---

src/main/java/io/github/hapjava/accessories/HomekitAccessory.java
src/main/java/io/github/hapjava/server/impl/json/AccessoryController.java

according to HAP spec one service should be marked as primary. this is especially important for accessories with multiple services.
```
2.3.2.3 Primary Service
Accessories should list one of its services as the primary service. The primary service must match the primary function of the accessory and must also match with the accessory category. An accessory must expose only one primary service from its list of available services.
```

mark primary service

---

src/main/java/io/github/hapjava/accessories/BasicFanAccessory.java
src/main/java/io/github/hapjava/services/impl/BasicFanService.java
src/main/java/io/github/hapjava/services/impl/FanService.java

the Home app doesn't let you customize the icon for a FanV2 (i.e. to show a ceiling fan).
I'm not sure if I'm ready to merge this yet. I've got it plumbed through to OpenHAB as well https://github.com/ccutrer/openhab-addons/commit/114fe0625d226098504a89243e763049abc53c42. When I tested, the accessory works as expected, EXCEPT that on iOS 16, the new Home refuses to show the fan anywhere except for if you go to the hub and list its accessories. Or if it's on it _does_ show on the top status line of a room. This feels like an iOS bug to me. So I'm going to let this hang out here until the next iOS update comes, and test again.

add back fanv1 service

---

src/main/java/io/github/hapjava/characteristics/impl/base/BaseCharacteristic.java

they're optional, and they just take up extra data

exclude characteristic description for well-known types

---

src/main/java/io/github/hapjava/characteristics/Characteristic.java
src/main/java/io/github/hapjava/characteristics/impl/base/BaseCharacteristic.java
src/main/java/io/github/hapjava/server/impl/HomekitRegistry.java
src/main/java/io/github/hapjava/server/impl/HomekitRoot.java
src/main/java/io/github/hapjava/server/impl/connections/SubscriptionManager.java
src/main/java/io/github/hapjava/server/impl/json/EventController.java

but the connection is _not_ torn down
also add the ability to modify accessories in a batch without having to regenerate all AIDs and IIDs (and other temporary data structures) at each intermediate step. You must use this mechanism if you plan on replacing an existing accessory with an equivalent one, but want to keep subscriptions intact.

keep subscriptions up to date when accessories are replaced

---

CHANGES.md
src/main/java/io/github/hapjava/server/HomekitAuthInfo.java
src/main/java/io/github/hapjava/server/impl/HomekitRoot.java
src/main/java/io/github/hapjava/server/impl/connections/HttpSession.java
src/main/java/io/github/hapjava/server/impl/jmdns/JmdnsHomekitAdvertiser.java
src/main/java/io/github/hapjava/server/impl/pairing/ErrorCode.java
src/main/java/io/github/hapjava/server/impl/pairing/ExchangeHandler.java
src/main/java/io/github/hapjava/server/impl/pairing/FinalPairHandler.java
src/main/java/io/github/hapjava/server/impl/pairing/MessageType.java
src/main/java/io/github/hapjava/server/impl/pairing/PairSetupManager.java
src/main/java/io/github/hapjava/server/impl/pairing/PairSetupRequest.java
src/main/java/io/github/hapjava/server/impl/pairing/PairVerifyManager.java
src/main/java/io/github/hapjava/server/impl/pairing/PairVerifyRequest.java
src/main/java/io/github/hapjava/server/impl/pairing/PairingMethod.java
src/main/java/io/github/hapjava/server/impl/pairing/PairingResponse.java
src/main/java/io/github/hapjava/server/impl/pairing/PairingUpdateController.java
src/main/java/io/github/hapjava/server/impl/pairing/PairingsManager.java
src/main/java/io/github/hapjava/server/impl/pairing/SrpHandler.java
src/main/java/io/github/hapjava/server/impl/pairing/Stage.java
src/main/java/io/github/hapjava/server/impl/pairing/TypeLengthValueUtils.java

also keep track of admin permissions for users
note that those permissions aren't actually enforced yet

improve pairing reliability with iOS 16.2

---

src/main/java/io/github/hapjava/server/impl/HomekitRegistry.java
src/main/java/io/github/hapjava/services/impl/AccessoryInformationService.java

in case someone is using some form of decorator or replacement class, but is still exposing the proper type

check for AccessoryInformationService by UUID, not by class

---

src/main/java/io/github/hapjava/characteristics/impl/base/BaseCharacteristic.java
src/main/java/io/github/hapjava/characteristics/impl/base/BooleanCharacteristic.java
src/main/java/io/github/hapjava/characteristics/impl/base/EnumCharacteristic.java
src/main/java/io/github/hapjava/characteristics/impl/base/FloatCharacteristic.java
src/main/java/io/github/hapjava/characteristics/impl/base/IntegerCharacteristic.java
src/main/java/io/github/hapjava/characteristics/impl/base/StaticStringCharacteristic.java
src/main/java/io/github/hapjava/characteristics/impl/base/StringCharacteristic.java

so they can also generically get the value, regardless of how they decided to fulfill it, without having to also keep track themselves

allow library users to get the value of characteristics themselves

---

CHANGES.md
src/main/java/io/github/hapjava/characteristics/impl/base/EnumCharacteristic.java
src/main/java/io/github/hapjava/characteristics/impl/common/ProgrammableSwitchEnum.java
src/main/java/io/github/hapjava/characteristics/impl/common/ProgrammableSwitchEventCharacteristic.java

* fix typo ProgrammableSwitchEnum
* allow restricting valid values

improve ProgrammableSwitchEvent

---

src/main/java/io/github/hapjava/characteristics/impl/television/RemoteKeyEnum.java
src/main/java/io/github/hapjava/server/impl/HomekitServer.java
src/main/java/io/github/hapjava/server/impl/HomekitStandaloneAccessoryServer.java

This pull requests fixes two issues:
- RemoteKeyEnum code for Info button is incorrect. Release version shows code 115, actual code is 15. Tested on IOS 16 and 15.
- Adds support for accessory category on standalone server. previously category was implemented for a bridge, but not for standalone accessories.

TelevisionAccessory Related Fixes
